# -*- coding: utf-8 -*-
"""Hackathon_HackTheCrisis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ESbRMgDbY6NNdpENv_TFpuRjw5DmoVUW
"""



import pandas as pd
DF = pd.read_csv('Genome_Data-X.csv')
DF['date'] = pd.to_datetime(DF['date']) #converting data column to data type
#DF = DF.loc[DF['Nuc.Completeness'] == 'Complete'] #only using rows which have complete genome data

DF.sort_values(by ='date',ascending = False, inplace= True)
DF = DF.head((len(DF)-6)) #deleting outlier data

import matplotlib.pyplot as plt
import matplotlib
import numpy as np

DF['sum'] = DF.apply(lambda
                         row: row.E_gene + row.M_gene + row.N_gene + row.S_gene + row.orf1ab + row.ORF3a + row.ORF6 + row.ORF7 + row.ORF8 + row.ORF10,
                     axis=1)
DF['sum_N'] =DF.apply(lambda
                         row: row.E_gene_N + row.M_gene_N + row.N_gene_N + row.S_gene_N + row.orf1ab_N + row.ORF3a_N + row.ORF6_N + row.ORF7_N + row.ORF8_N + row.ORF10_N,
                     axis=1)
def chart(gene,l_n, plot_color = 'blue'): #function which makes logarythmic/normal plot based on a column from dataframe

  if 'whole' in gene:
      temp_df = DF
  elif '_translation' in gene:
      temp_df = DF[DF[gene.split('_t')[0] + '_N'] == 0]
  else:temp_df = DF[DF[gene+'_N'] == 0]
  list_of_datetimes = temp_df['date'].tolist()
  dates = matplotlib.dates.date2num(list_of_datetimes)
  values = temp_df[gene].tolist()
  if l_n == 'l':
    values = np.log(values)
  x = plt.plot_date(dates, values, color=plot_color, alpha = 0.2)

  plt.title( gene +' of SARS-CoV-2', loc='left',fontsize = 10)
  plt.ylabel('Mutations', fontsize = 10)
  plt.xlabel('Time')
  plt.xticks(fontsize = 10, rotation=35)
  plt.tight_layout()
  #plt.savefig(gene + '.png')



Genes = [ 'E_gene', 'M_gene', 'S_gene', 'N_gene','orf1ab', 'ORF6', 'ORF7', 'ORF8', 'ORF10','ORF3a']
a=1

for gene in Genes:

    plt.subplot(1,2,1)
    chart(gene, 'e')
    plt.subplot(1, 2, 2)
    chart(gene + '_translation', 'e', 'red')
    plt.savefig('plots/'+ gene + '.png')
    plt.show()
chart('sum', 'e')
plt.savefig('plots/whole_genome' + '.png')
plt.show()

