GOOGLE_CHARTS_COUNTRIES_NAMES = {
    "USA": "US",
    "PuertoRico": "US",
    "Guam": "US",
    "CzechRepublic": "Czech Republic",
    "Australia": "Australia",
    "Spain": "Spain",
    "Scotland": "United Kingdom",
    "Lebanon": "Lebanon",
    "Italy": "Italy",
    "Mexico": "Mexico",
    "Iran": "Iran",
    "India": "India",
    "Turkey": "Turkey",
    "Iceland": "Iceland",
    "NorthernIreland": "United Kingdom",
    "Japan": "Japan",
    "England": "United Kingdom",
    "Taiwan": "Taiwan",
    "France": "France",
    "JAM": "Jamaica",
    "Finland": "Finland",
    "Wales": "United Kingdom",
    "Sweden": "Sweden",
    "SouthAfrica": "South Africa",
    "SouthKorea": "South Korea",
    "Belgium": "Belgium",
    "Russia": "Russia",
    "Switzerland": "Switzerland",
    "Brazil": "Brazil",
    "Korea": "South Korea",
    "Hungary": "Hungary",
    "Lithuania": "Lithuania",
    "Austria": "Austria",
    "Georgia": "Georgia",
    "Poland": "Poland",
    "Netherlands": "Netherlands",
    "Ireland": "Ireland",
    "Germany": "Germany",
    "Myanmar": "Myanmar",
    "Pakistan": "Pakistan",
    "Norway": "Norway",
    "Indonesia": "Indonesia",
    "Jordan": "Jordan",
    "Argentina": "Argentina",
    "Croatia": "Croatia",
    "Slovakia": "Slovakia",
    "Egypt": "Egypt",
    "Peru": "Peru",
    "Estonia": "Estonia",
    "Belarus": "Belarus",
    "Serbia": "Serbia",
    "Portugal": "Portugal",
    "Vietnam": "Vietnam",
    "Uruguay": "Uruguay",
    "Chile": "Chile",
    "Malaysia": "Malaysia",
    "Latvia": "Latvia",
    "Singapore": "Singapore",
    "Slovenia": "Slovenia",
    "Luxembourg": "Luxembourg",
    "Senegal": "Senegal",
    "Canada": "Canada",
    "Greece": "Greece",
    "Algeria": "Algeria",
    "Colombia": "Colombia",
    "Nigeria": "Nigeria",
    "Kazakhstan": "Kazakhstan",
    "Ecuador": "Ecuador",
    "Nepal": "Nepal",
    "Ghana": "Ghana",
    "Jingzhou": "China",
    "Hefei": "China",
    "HongKong": "China",
    "Guangzhou": "China",
    "Shandong": "China",
    "Fuyang": "China",
    "Beijing": "China",
    "Chongqing": "China",
    "Yunnan": "China",
    "Guangxi": "China",
    "Sichuan": "China",
    "Jiangxi": "China",
    "Henan": "China",
    "Lishui": "China",
    "NanChang": "China",
    "Jiujiang": "China",
    "Nanchang": "China",
    "Shangrao": "China",
    "Ganzhou": "China",
    "Xinyu": "China",
    "Pingxiang": "China",
    "Jian": "China",
    "Jiangsu": "China",
    "China": "China",
    "Foshan": "China",
    "Shenzhen": "China",
    "Fujian": "China",
    "Zhejiang": "China",
    "Wuhan-Hu-1": "China",
    "Hangzhou": "China",
    "Guangdong": "China",
    "Anhui": "China",
    "Shanghai": "China",
    "Wuhan": "China",
    "SriLanka": "Sri Lanka",
    "Philippines": "Philippines",
    "Denmark": "Denmark",
    "NetherlandsL": "Netherlands",
    "Israel": "Israel",
    "SaudiArabia": "Saudi Arabia",
    "NewZealand": "New Zealand",
    "UnitedArabEmirates": "United Arab Emirates",
    "Thailand": "Thailand",
    "CostaRica": "Costa Rica",
    "Romania": "Romania",
    "Brunei": "Brunei",
    "Bangladesh": "Bangladesh",
    "Kuwait": "Kuwait",
    "Gambia": "Gambia",
    "Cambodia": "Cambodia",
    "DRC": "CD", #Democratic Republic of the Congo
}
